export const usersCustomer: any[] = [
  {
    "username": "Erick Cinco",
    "email": "erickcincoa@gmail.com",
    "country_code": 52,
    "phone": 6691438664,
    "password": "#TestPass.",
  },
  {
    "username": "Mariana Ortela",
    "email": "marianaortela@gmail.com",
    "country_code": 52,
    "phone": 5599873421,
    "password": "#TestPass.",
  },
  {
    "username": "Juan Cinco",
    "email": "juancinco@gmail.com",
    "country_code": 52,
    "phone": 6691438666,
    "password": "#TestPass.",
  },
  {
    "username": "Pedro Suarez",
    "email": "pedrosuarez@gmail.com",
    "country_code": 52,
    "phone": 5566224411,
    "password": "#TestPass.",
  },
  {
    "username": "Manuel Villalobo",
    "email": "manuelvillalobo@gmail.com",
    "country_code": 52,
    "phone": 5566772233,
    "password": "#TestPass.",
  },
  {
    "username": "Bryto Osuna",
    "email": "brytosuna@gmail.com",
    "country_code": 52,
    "phone": 6692346587,
    "password": "#TestPass.",
  },
  {
    "username": "Irving Contreras",
    "email": "irvingcontreras@gmail.com",
    "country_code": 52,
    "phone": 6693452312,
    "password": "#TestPass.",
  },
  {
    "username": "Enrique Ferraz",
    "email": "enriqueferraz@gmail.com",
    "country_code": 52,
    "phone": 6691657876,
    "password": "#TestPass.",
  },
  {
    "username": "Aaron Villavicencio",
    "email": "villavicencio@gmail.com",
    "country_code": 52,
    "phone": 5567340122,
    "password": "#TestPass.",
  },
  {
    "username": "Rene Perez",
    "email": "reneperez@gmail.com",
    "country_code": 52,
    "phone": 6691434221,
    "password": "#TestPass.",
  },
  {
    "username": "Claudia Rodriguez",
    "email": "claudiarodriguez@gmail.com",
    "country_code": 52,
    "phone": 6691500098,
    "password": "#TestPass.",
  },
  {
    "username": "Claudia Guzman",
    "email": "claudiaguzman@gmail.com",
    "country_code": 52,
    "phone": 6680009082,
    "password": "#TestPass.",
  },
  {
    "username": "Karen Estrada",
    "email": "karenestrada@gmail.com",
    "country_code": 52,
    "phone": 6691343434,
    "password": "#TestPass.",
  },
];